<?php

/**
 * W3C Payment Request (https://www.w3.org/TR/payment-request/)
 *
 * Add the W3C payment request api to Magento 2
 *
 * @package     ImaginationMedia\PaymentRequest
 * @author      Igor Ludgero Miura <igor@imaginationmedia.com>
 * @copyright   Copyright (c) 2019 Imagination Media (https://www.imaginationmedia.com/)
 * @license     https://opensource.org/licenses/OSL-3.0.php Open Software License 3.0
 */

/**
 * @var $block \Magento\Framework\View\Element\Js\Components
 */

?>

<div id="paymentRequest" data-bind="scope: 'paymentRequest'">
    <script type="text/x-magento-init">
        {"#paymentRequest": {"Magento_Ui/js/core/app": <?php echo $block->getJsLayout();?>}}
    </script>
</div>
